objects/LLC_BI__Loan_Collateral__c.object
<CustomObject>
    <description>The Collateral object contains information about the pieces of collateral used to secure a loan</description>
    <fields>
        <fullName>LLC_BI__Loan__c</fullName>
        <description>This field is optional and manually populated. Use this field as an external unique key for a loan to link the collateral to a loan.</description>
        <label>Loan</label>
        <referenceTo>LLC_BI__Loan__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Collateral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__Field_Configuration__c.object
<CustomObject>
    <description>Extends a field for the given object with additional features. Can be optionally tied to Routes.</description>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Route. If none is specified the Field Configuration can be applied everywhere.</description>
        <inlineHelpText>Specify the Route that this Field Configuration will apply to, otherwise it will be applied everywhere.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Field Configuration Route</relationshipLabel>
        <relationshipName>Field_Configuration_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. It is used to specify a screen section which this record should be applied to.</description>
        <label>Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Field Configurations</relationshipLabel>
        <relationshipName>Section_Field_Configuration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records, when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Field Configuration</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>Field Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Group__c.object
<CustomObject>
    <description>Generalized grouping object.</description>
    <fields>
        <fullName>nFORCE__App__c</fullName>
        <description>This field is manually populated. It is required. This field is a unique identifier for the group and is used, in conjunction with a route&apos;s app, to uniquely identify a requested app.</description>
        <inlineHelpText>Enter the group portion of the requested app.

E.g. If the requested app is &apos;loan.change-product&apos;, then the group portion is &apos;loan&apos;.</inlineHelpText>
        <label>App</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Use this lookup field to select the layout for the group.</description>
        <inlineHelpText>Select a layout for this group.</inlineHelpText>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</description>
        <inlineHelpText>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__App__c</fullName>
        <description>This field is manually populated. It is required. This field is a unique identifier for the route, and is used, in conjunction with a group&apos;s app, to uniquely identify a requested app.</description>
        <inlineHelpText>This is the unique identifier similar to the Salesforce.com API Name.</inlineHelpText>
        <label>App</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <description>--DEPRECATED--

            Moved to Group__c.</description>
        <label>-D Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. This field looks up to the screen, which is typically used to determine what fields to display, and the view state (read only or editable) to display them in.</description>
        <inlineHelpText>Screens are a collection of  Screen Sections which reference field sets.  LLC_BI Routes commonly reference visualforce pages, thus do not require a screen.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route_Group__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the group a route is being linked to.</description>
        <inlineHelpText>Choose a group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>nFORCE__Group__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the route a group is being linked to.</description>
        <inlineHelpText>Choose a route.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Route Group</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Route Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Screen_Section__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is currently not being used.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <description>This field is optional. It is automatically populated whenever a screen section is created from the screen. This field specifies the screen associated with the screen section.</description>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Screen Section</label>
    <nameField>
        <label>Screen Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__Section_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is optional. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the layout associated with the section configuration. It specifies the layout of the fields in the credit memo for the field set associated with this record.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_Section__c</fullName>
        <description>This field is required. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the screen section associated with the section configuration. It provides the screen section with the fields to be used.</description>
        <label>Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Configuration</label>
    <nameField>
        <displayFormat>SC-{000000000}</displayFormat>
        <label>Section Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserInterfaceLookupKeyUtilityTest.cls
@isTest
private class UserInterfaceLookupKeyUtilityTest
{
    /**TEST METHODS**/
    
    @isTest
    static void lookupKeyTestDriver()
    {
        nFORCE__Group__c group1 = createGroup('Group A', 'group-a', 'group-001');
        nFORCE__Screen__c screen1 = createScreen('Screen A', 'screen-001');
        nFORCE__Screen__c screen2 = createScreen('Screen B', 'screen-002');
        nFORCE__Screen__c screen3 = createScreen('Screen C', 'screen-003');
        nFORCE__Screen__c screen4 = createScreen('Screen D', 'screen-004');
        nFORCE__Route__c route1 = createRoute('Route One', 'route-A', 'test-body1', screen1.Id, 'route-001');
        nFORCE__Route__c route2 = createRoute('Route One', 'route-B', 'test-body2', screen2.Id, 'route-002');  
        nFORCE__Route__c route3 = createRoute('Route C', 'action-route-c', 'test-body3', screen3.Id, 'route-003');
        nFORCE__Route__c route4 = createRoute('Route C', 'tool-route-c', 'test-body3', screen4.Id, 'route-004');
        nFORCE__Route_Group__c routegroup1 = createRouteGroup(group1.Id, route1.Id, null, 'routegroup-001');
        nFORCE__Route_Group__c routegroup2 = createRouteGroup(group1.Id, route2.Id, route2.Id, 'routegroup-002');
        nFORCE__Route_Group__c routegroup3 = createRouteGroup(group1.Id, route3.Id, null, 'routegroup-003');
        nFORCE__Route_Group__c routegroup4 = createRouteGroup(group1.Id, route4.Id, null, 'routegroup-004');  
        nFORCE__View__c view1 = createView('view-001');
        nFORCE__View__c view2 = createView('view-002');
        nFORCE__Screen_Section__c screensection1 = createScreenSection('ScreenSection1', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen1.Id, view1.Id, 'screensection-001');
        nFORCE__Screen_Section__c screensection2 = createScreenSection('ScreenSection2', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, view2.Id, 'screensection-002');
        nFORCE__Screen_Section__c screensection3 = createScreenSection('ScreenSection3', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, null, 'screensection-003');
        nFORCE__Layout__c layout1 = createLayout('NoLayout', 'Html.Layouts.NoLayout', 'layout-001');
        nFORCE__Layout__c layout2 = createLayout('NoLayout', 'Html.Layouts.NoLayout', 'layout-002');
        nFORCE__Layout__c layout3 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', 'layout-003');
        nFORCE__Layout__c layout4 = createLayout('NoLayout', 'Html.Layouts.NoLayout', 'layout-004');
        nFORCE__Layout__c layout5 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', 'layout-005');                                        
        nFORCE__Section_Configuration__c sectionconfig1 = createSectionConfiguration(screensection1.Id, null, layout1.Id, null, 'ABC937523872', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig2 = createSectionConfiguration(screensection2.Id, null, layout2.Id, null, 'DEF283957235', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig3 = createSectionConfiguration(screensection2.Id, sectionconfig2.Id, layout3.Id, 'LLC_BI__Collateral__r', 'GHI87346346', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Section_Configuration__c sectionconfig4 = createSectionConfiguration(screensection3.Id, null, layout4.Id, null, 'JKL289357239', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig5 = createSectionConfiguration(screensection3.Id, sectionconfig4.Id, layout5.Id, 'LLC_BI__Collateral__r', 'MNO984376487', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Field_Configuration__c fieldconfig1 = createFieldConfiguration(route1.Id, screensection1.Id, 'Name', 'LLC_BI__Loan__c', 'fieldconfig-001');
        nFORCE__Field_Configuration__c fieldconfig2 = createFieldConfiguration(route2.Id, screensection2.Id, 'Name', 'LLC_BI__Loan__c', 'fieldconfig-002');
        
        Test.setCurrentPageReference(new PageReference('Page.UserInterfaceDeepClonePage'));
        System.currentPageReference().getParameters().put('id', group1.Id); //objectId
        
        UserInterfaceLookupKeyUtility lookupKeyContainer = new UserInterfaceLookupKeyUtility(); //for coverage of empty constructor
        //UserInterfaceDeepClone clone = new UserInterfaceDeepClone(new ApexPages.StandardController(group1));
        //clone.newGroupName ='Test New Group';
        lookupKeyContainer.analyzeKeys();
    }
    
    @isTest
    static void lookupKeyTestDriver2()
    {
        nFORCE__Group__c group1 = createGroup('Group A', 'group-a', '');
        nFORCE__Screen__c screen1 = createScreen('Screen A', '');
        nFORCE__Screen__c screen2 = createScreen('Screen B', '');
        nFORCE__Screen__c screen3 = createScreen('Screen C', '');
        nFORCE__Screen__c screen4 = createScreen('Screen D', '');
        nFORCE__Route__c route1 = createRoute('Route One', 'route-A', 'test-body1', screen1.Id, '');
        nFORCE__Route__c route2 = createRoute('Route One', 'route-B', 'test-body2', screen2.Id, '');  
        nFORCE__Route__c route3 = createRoute('Route C', 'action-route-c', 'test-body3', screen3.Id, '');
        nFORCE__Route__c route4 = createRoute('Route C', 'tool-route-c', 'test-body3', screen4.Id, '');
        nFORCE__Route_Group__c routegroup1 = createRouteGroup(group1.Id, route1.Id, null, '');
        nFORCE__Route_Group__c routegroup2 = createRouteGroup(group1.Id, route2.Id, route2.Id, '');
        nFORCE__Route_Group__c routegroup3 = createRouteGroup(group1.Id, route3.Id, null, '');
        nFORCE__Route_Group__c routegroup4 = createRouteGroup(group1.Id, route4.Id, null, '');  
        nFORCE__View__c view1 = createView('');
        nFORCE__View__c view2 = createView('');
        nFORCE__Screen_Section__c screensection1 = createScreenSection('ScreenSection1', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen1.Id, view1.Id, '');
        nFORCE__Screen_Section__c screensection2 = createScreenSection('ScreenSection2', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, view2.Id, '');
        nFORCE__Screen_Section__c screensection3 = createScreenSection('ScreenSection3', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, null, '');
        nFORCE__Layout__c layout1 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout2 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout3 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', '');
        nFORCE__Layout__c layout4 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout5 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', '');                                        
        nFORCE__Section_Configuration__c sectionconfig1 = createSectionConfiguration(screensection1.Id, null, layout1.Id, null, 'sc001', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig2 = createSectionConfiguration(screensection2.Id, null, layout2.Id, null, 'sc002', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig3 = createSectionConfiguration(screensection2.Id, sectionconfig2.Id, layout3.Id, 'LLC_BI__Collateral__r', 'sc003', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Section_Configuration__c sectionconfig4 = createSectionConfiguration(screensection3.Id, null, layout4.Id, null, 'sc004', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig5 = createSectionConfiguration(screensection3.Id, sectionconfig4.Id, layout5.Id, 'LLC_BI__Collateral__r', 'sc005', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Field_Configuration__c fieldconfig1 = createFieldConfiguration(route1.Id, screensection1.Id, 'Name', 'LLC_BI__Loan__c', '');
        nFORCE__Field_Configuration__c fieldconfig2 = createFieldConfiguration(route2.Id, screensection2.Id, 'Name', 'LLC_BI__Loan__c', '');
        
        Test.setCurrentPageReference(new PageReference('Page.UserInterfaceDeepClonePage'));
        System.currentPageReference().getParameters().put('id', group1.Id); //objectId
        
        UserInterfaceLookupKeyUtility lookupKeyContainer = new UserInterfaceLookupKeyUtility(); //for coverage of empty constructor
        //UserInterfaceDeepClone clone = new UserInterfaceDeepClone(new ApexPages.StandardController(group1));
        //clone.newGroupName ='Test New Group';
        lookupKeyContainer.analyzeKeys();
    }
    
    @isTest
    static void lookupKeyTestDriver3()
    {
        nFORCE__Group__c group1 = createGroup('Group A', 'group-a', '');
        nFORCE__Screen__c screen1 = createScreen('Screen A', '');
        nFORCE__Screen__c screen2 = createScreen('Screen B', '');
        nFORCE__Screen__c screen3 = createScreen('Screen C', '');
        nFORCE__Screen__c screen4 = createScreen('Screen D', '');
        nFORCE__Route__c route1 = createRoute('Route One', 'route-A', 'test-body1', screen1.Id, '');
        nFORCE__Route__c route2 = createRoute('Route One', 'route-B', 'test-body2', screen2.Id, '');  
        nFORCE__Route__c route3 = createRoute('Route C', 'action-route-c', 'test-body3', screen3.Id, '');
        nFORCE__Route__c route4 = createRoute('Route C', 'tool-route-c', 'test-body3', screen4.Id, '');
        nFORCE__Route_Group__c routegroup1 = createRouteGroup(group1.Id, route1.Id, null, '');
        nFORCE__Route_Group__c routegroup2 = createRouteGroup(group1.Id, route2.Id, route2.Id, '');
        nFORCE__Route_Group__c routegroup3 = createRouteGroup(group1.Id, route3.Id, null, '');
        nFORCE__Route_Group__c routegroup4 = createRouteGroup(group1.Id, route4.Id, null, '');  
        nFORCE__View__c view1 = createView('');
        nFORCE__View__c view2 = createView('');
        nFORCE__Screen_Section__c screensection1 = createScreenSection('ScreenSection1', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen1.Id, view1.Id, '');
        nFORCE__Screen_Section__c screensection2 = createScreenSection('ScreenSection2', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, view2.Id, '');
        nFORCE__Screen_Section__c screensection3 = createScreenSection('ScreenSection3', 'LLC_BI__Loan__c', 'MappedSObjectHierarchyResource', screen2.Id, null, '');
        nFORCE__Layout__c layout1 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout2 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout3 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', '');
        nFORCE__Layout__c layout4 = createLayout('NoLayout', 'Html.Layouts.NoLayout', '');
        nFORCE__Layout__c layout5 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid', '');                                        
        nFORCE__Section_Configuration__c sectionconfig1 = createSectionConfiguration(screensection1.Id, null, layout1.Id, null, 'sc001', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig2 = createSectionConfiguration(screensection2.Id, null, layout2.Id, null, 'sc002', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig3 = createSectionConfiguration(screensection2.Id, sectionconfig2.Id, layout3.Id, 'LLC_BI__Collateral__r', 'sc003', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Section_Configuration__c sectionconfig4 = createSectionConfiguration(screensection3.Id, null, layout4.Id, null, 'sc004', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig5 = createSectionConfiguration(screensection3.Id, sectionconfig4.Id, layout5.Id, 'LLC_BI__Collateral__r', 'sc005', 'LLC_BI__Loan__c', 2.01);
        nFORCE__Field_Configuration__c fieldconfig1 = createFieldConfiguration(route1.Id, screensection1.Id, 'Name', 'LLC_BI__Loan__c', '');
        nFORCE__Field_Configuration__c fieldconfig2 = createFieldConfiguration(route2.Id, screensection2.Id, 'Name', 'LLC_BI__Loan__c', '');
        
        Test.setCurrentPageReference(new PageReference('Page.UserInterfaceDeepClonePage'));
        System.currentPageReference().getParameters().put('id', group1.Id); //objectId
        
        UserInterfaceLookupKeyUtility lookupKeyContainer = new UserInterfaceLookupKeyUtility(); //for coverage of empty constructor
        //UserInterfaceDeepClone clone = new UserInterfaceDeepClone(new ApexPages.StandardController(group1));
        //clone.newGroupName ='Test New Group';
        lookupKeyContainer.assignKeys();
    }

    /**OBJECT CREATION METHODS**/

    private static nFORCE__Group__c createGroup(String n, String app, String lky)
    {
        nFORCE__Group__c newGroup = new nFORCE__Group__c(Name = n, nFORCE__App__c = app, nFORCE__lookupKey__c = lky);
        insert newGroup;
        return newGroup;
    }
    
    private static nFORCE__Route__c createRoute(String n, String app, String body, Id screen, String lky)
    {
        nFORCE__Route__c newRoute = new nFORCE__Route__c(Name = n, nFORCE__App__c = app, nFORCE__Body__c = body, nFORCE__Screen__c = screen, nFORCE__lookupKey__c = lky);
        insert newRoute;
        return newRoute;
    }
    
    private static nFORCE__Route_Group__c createRouteGroup(Id grp, Id route, Id route_group, String lky)
    {
        nFORCE__Route_Group__c newRouteGroup = new nFORCE__Route_Group__c(nFORCE__Group__c = grp, nFORCE__Route__c = route, nFORCE__Parent_Route__c = route_group, nFORCE__lookupKey__c = lky);
        insert newRouteGroup;
        return newRouteGroup;
    }
    
    private static nFORCE__Screen__c createScreen(String n, String lky)
    {
        nFORCE__Screen__c newScreen = new nFORCE__Screen__c(Name = n, nFORCE__lookupKey__c = lky);
        insert newScreen;
        return newScreen;
    }
    
    private static nFORCE__Screen_Section__c createScreenSection(String n, String sobj, String resource, Id screen, Id view, String lky)
    {
        nFORCE__Screen_Section__c newScreenSection = new nFORCE__Screen_Section__c(Name = n, nFORCE__sObject_Type__c = sobj, 
            nFORCE__Section_Resource__c = resource, nFORCE__Screen__c = screen, nFORCE__Screen_View__c = view, nFORCE__lookupKey__c = lky);
        insert newScreenSection;
        return newScreenSection;
    }
    
    private static nFORCE__View__c createView(String lky)
    {
        nFORCE__View__c newView = new nFORCE__View__c(nFORCE__lookupKey__c = lky);
        insert newView;
        return newView;
    }
    
    private static nFORCE__Section_Configuration__c createSectionConfiguration(Id screensection, Id parent_config, Id layout, String parent_name, String lky, String sotype, Decimal order)
    {
        nFORCE__Section_Configuration__c newSectionConfig = new nFORCE__Section_Configuration__c(nFORCE__Screen_Section__c = screensection, 
            nFORCE__Parent_Configuration__c = parent_config, nFORCE__Parent_Relationship_Name__c = parent_name, nFORCE__lookupKey__c = lky,
            nFORCE__sObject_Type__c = sotype, nFORCE__Display_Order__c = order, nFORCE__Layout__c = layout);
        insert newSectionConfig;
        return newSectionConfig;
    }
    
    private static nFORCE__Layout__c createLayout(String nm, String genclass, String lky)
    {
        nFORCE__Layout__c newLayout = new nFORCE__Layout__c(Name = nm, nFORCE__Generator_Class__c = genclass, nFORCE__lookupKey__c = lky);
        insert newLayout;
        return newLayout;
    }
    
    private static nFORCE__Field_Configuration__c createFieldConfiguration(Id route, Id ssection, String fname, String oname, String lky)
    {
        nFORCE__Field_Configuration__c newFieldConfig = new nFORCE__Field_Configuration__c(nFORCE__Route__c = route, nFORCE__Screen_Section__c = ssection, 
            nFORCE__Field_Name__c = fname, nFORCE__sObject_Name__c = oname, nFORCE__lookupKey__c = lky);
        insert newFieldConfig;
        return newFieldConfig;
    }  
}