objects/LLC_BI__Loan_Collateral__c.object
<CustomObject>
    <description>The Collateral object contains information about the pieces of collateral used to secure a loan</description>
    <fields>
        <fullName>LLC_BI__Loan__c</fullName>
        <description>This field is optional and manually populated. Use this field as an external unique key for a loan to link the collateral to a loan.</description>
        <label>Loan</label>
        <referenceTo>LLC_BI__Loan__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Collateral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__Group__c.object
<CustomObject>
    <description>Generalized grouping object.</description>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Use this lookup field to select the layout for the group.</description>
        <inlineHelpText>Select a layout for this group.</inlineHelpText>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</description>
        <inlineHelpText>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Layout__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records, when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm).</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Layout</label>
    <nameField>
        <label>Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <description>--DEPRECATED--

            Moved to Group__c.</description>
        <label>-D Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. This field looks up to the screen, which is typically used to determine what fields to display, and the view state (read only or editable) to display them in.</description>
        <inlineHelpText>Screens are a collection of  Screen Sections which reference field sets.  LLC_BI Routes commonly reference visualforce pages, thus do not require a screen.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route_Group__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the group a route is being linked to.</description>
        <inlineHelpText>Choose a group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>nFORCE__Group__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the route a group is being linked to.</description>
        <inlineHelpText>Choose a route.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Route Group</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Route Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Screen_Section__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is currently not being used.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_View__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is optional. It is automatically populated by the Layout Builder tool on the screen section. This field specifies the screen view associated with the screen section. This field is typically used with the credit memo. It provides the credit memo with the code used to generate the fields and their layout.</description>
        <label>Screen View</label>
        <referenceTo>nFORCE__View__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <description>This field is optional. It is automatically populated whenever a screen section is created from the screen. This field specifies the screen associated with the screen section.</description>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>nFORCE__Section_Resource__c</fullName>
        <description>This field is required. It is manually populated. This field specifies how the screen section obtains the data to be displayed. The values SObjectScreenResource and ConfiguredSObjectScreenResource use coded screen resources to display data. The values MappedSObjectScreenResource, MappedSObjectHierarchyScreenResource, MappedSObjectListScreenResource, and ReferenceFilteredHierarchyScreenResource use the Layout Builder tool to determine what data to display.</description>
        <label>Section Resource</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SObjectScreenResource</fullName>
                </value>
                <value>
                    <fullName>ConfiguredSObjectScreenResource</fullName>
                </value>
                <value>
                    <fullName>MappedSObjectScreenResource</fullName>
                </value>
                <value>
                    <fullName>MappedSObjectHierarchyScreenResource</fullName>
                </value>
                <value>
                    <fullName>GrandchildScreenResource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Screen Section</label>
    <nameField>
        <label>Screen Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__Section_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is optional. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the layout associated with the section configuration. It specifies the layout of the fields in the credit memo for the field set associated with this record.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Parent_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is optional. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies a parent layout associated with the layout record you are viewing. Parent layouts are used to ensure parent-child navigational integreity between section configurations, as well as determining the display order.</description>
        <label>Parent Configuration</label>
        <referenceTo>nFORCE__Section_Configuration__c</referenceTo>
        <relationshipLabel>Child Configurations</relationshipLabel>
        <relationshipName>Child_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Parent_Relationship_Name__c</fullName>
        <description>This field is optional. It is populated automatically by the Layout Builder tool on the parent screen section. It is used to store parent-child navigational data, so the screen section can properly display data on child or parent objects of the screen section&apos;s sObject_Type (value in nFORCE__sObject_Type__c field).</description>
        <label>Parent Relationship Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_Section__c</fullName>
        <description>This field is required. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the screen section associated with the section configuration. It provides the screen section with the fields to be used.</description>
        <label>Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Configuration</label>
    <nameField>
        <displayFormat>SC-{000000000}</displayFormat>
        <label>Section Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UIRemoveGroupControllerTest.cls
@isTest
private class UIRemoveGroupControllerTest
{  
    @isTest
    static void groupRedirectSuccess1()
    {
        nFORCE__Screen__c testScreen = createScreen();
        nFORCE__Group__c testGroup = createGroup();
        nFORCE__Route__c testRoute = createRoute(testScreen.Id);
        nFORCE__Route_Group__c testRouteGroup = createRouteGroup(testGroup.Id, testRoute.Id);
        nFORCE__View__c testScreenView = createView();
        nFORCE__Screen_Section__c testScreenSection = createScreenSection(testScreen.Id, testScreenView.Id);
        nFORCE__Layout__c layout1 = createLayout('NoLayout', 'Html.Layouts.NoLayout');
        nFORCE__Layout__c layout2 = createLayout('TwoColumnGrid', 'Html.Layouts.TwoColumnGrid');      
        
        nFORCE__Section_Configuration__c sectionconfig1 = createSectionConfiguration(testScreenSection.Id, null, layout1.Id, null, 'DEF283957235', 'LLC_BI__Loan__c', 1.01);
        nFORCE__Section_Configuration__c sectionconfig2 = createSectionConfiguration(testScreenSection.Id, sectionconfig1.Id, layout2.Id, 'LLC_BI__Collateral__r', 'GHI87346346', 'LLC_BI__Loan__c', 2.01);        
        
        UIRemoveGroupController remove = new UIRemoveGroupController(new ApexPages.StandardController(new nFORCE__Group__c()));
        
        //Inserting Related List Screen Sections
        Test.startTest();
        remove.RecordId = testGroup.Id;
        remove.groupRedirect();
        Test.stopTest();
    }

    private static nFORCE__Group__c  createGroup()
    {
        nFORCE__Group__c newGroup = new nFORCE__Group__c(Name = 'TestGroup');
        insert newGroup;
        return newGroup;
    }

    private static nFORCE__Route__c createRoute(Id screen)
    {
        nFORCE__Route__c newRoute = new nFORCE__Route__c(nFORCE__Screen__c = screen, Name = 'GenRoute1');
        insert newRoute;
        return newRoute;
    }
    
    private static nFORCE__Route_Group__c createRouteGroup(Id groupId, Id routeId)
    {
        nFORCE__Route_Group__c newRouteGroup = new nFORCE__Route_Group__c(nFORCE__Group__c = groupId, nFORCE__Route__c = routeId);
        insert newRouteGroup;
        return newRouteGroup;
    }
    
    private static nFORCE__Screen__c createScreen()
    {
        nFORCE__Screen__c newScreen = new nFORCE__Screen__c(Name = 'TestScreen');
        insert newScreen;
        return newScreen;
    }
    
    private static nFORCE__Screen_Section__c createScreenSection(Id screenId, Id view)
    {
        nFORCE__Screen_Section__c newScreenSection = new nFORCE__Screen_Section__c(nFORCE__Section_Resource__c = 'SObjectScreenResource',
            nFORCE__Screen__c = screenId, nFORCE__Screen_View__c = view);
        insert newScreenSection;
        return newScreenSection;
    }
    
    private static nFORCE__View__c createView()
    {
        nFORCE__View__c newView = new nFORCE__View__c();
        insert newView;
        return newView;
    }
    
    private static nFORCE__Section_Configuration__c createSectionConfiguration(Id screensection, Id parent_config, Id layout, String parent_name, String lky, String sotype, Decimal order)
    {
        nFORCE__Section_Configuration__c newSectionConfig = new nFORCE__Section_Configuration__c(nFORCE__Screen_Section__c = screensection, 
            nFORCE__Parent_Configuration__c = parent_config, nFORCE__Parent_Relationship_Name__c = parent_name, nFORCE__lookupKey__c = lky,
            nFORCE__sObject_Type__c = sotype, nFORCE__Display_Order__c = order, nFORCE__Layout__c = layout);
        insert newSectionConfig;
        return newSectionConfig;
    }    
    
    private static nFORCE__Layout__c createLayout(String nm, String genclass)
    {
        nFORCE__Layout__c newLayout = new nFORCE__Layout__c(Name = nm, nFORCE__Generator_Class__c = genclass);
        insert newLayout;
        return newLayout;
    }
}