objects/nFORCE__Field_Configuration__c.object
<CustomObject>
    <description>Extends a field for the given object with additional features. Can be optionally tied to Routes.</description>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Route. If none is specified the Field Configuration can be applied everywhere.</description>
        <inlineHelpText>Specify the Route that this Field Configuration will apply to, otherwise it will be applied everywhere.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Field Configuration Route</relationshipLabel>
        <relationshipName>Field_Configuration_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. It is used to specify a screen section which this record should be applied to.</description>
        <label>Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Field Configurations</relationshipLabel>
        <relationshipName>Section_Field_Configuration</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Configuration</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>Field Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Group__c.object
<CustomObject>
    <description>Generalized grouping object.</description>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Use this lookup field to select the layout for the group.</description>
        <inlineHelpText>Select a layout for this group.</inlineHelpText>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</description>
        <inlineHelpText>The Screen used to render the content of this group. In the nCino UI this Screen will render in the Topbar.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Layout__c.object
<CustomObject>
    <label>Layout</label>
    <nameField>
        <label>Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Layout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <description>--DEPRECATED--

            Moved to Group__c.</description>
        <label>-D Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. This field looks up to the screen, which is typically used to determine what fields to display, and the view state (read only or editable) to display them in.</description>
        <inlineHelpText>Screens are a collection of  Screen Sections which reference field sets.  LLC_BI Routes commonly reference visualforce pages, thus do not require a screen.</inlineHelpText>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route_Group__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the group a route is being linked to.</description>
        <inlineHelpText>Choose a group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>nFORCE__Group__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the route a group is being linked to.</description>
        <inlineHelpText>Choose a route.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Route Group</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Route Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Screen__c.object
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Screen_Section__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is currently not being used.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Parent_Screen_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. This field is used for conditional field rendering. It specifies the screen section a conditional screen section is associated to.</description>
        <label>Parent Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_View__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is optional. It is automatically populated by the Layout Builder tool on the screen section. This field specifies the screen view associated with the screen section. This field is typically used with the credit memo. It provides the credit memo with the code used to generate the fields and their layout.</description>
        <label>Screen View</label>
        <referenceTo>nFORCE__View__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen__c</fullName>
        <description>This field is optional. It is automatically populated whenever a screen section is created from the screen. This field specifies the screen associated with the screen section.</description>
        <label>Screen</label>
        <referenceTo>nFORCE__Screen__c</referenceTo>
        <relationshipLabel>Screen Sections</relationshipLabel>
        <relationshipName>Screen_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Screen Section</label>
    <nameField>
        <label>Screen Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__Section_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is optional. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the layout associated with the section configuration. It specifies the layout of the fields in the credit memo for the field set associated with this record.</description>
        <label>Layout</label>
        <referenceTo>nFORCE__Layout__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Screen_Section__c</fullName>
        <description>This field is required. It is populated automatically by the Layout Builder tool on the parent screen section. This field specifies the screen section associated with the section configuration. It provides the screen section with the fields to be used.</description>
        <label>Screen Section</label>
        <referenceTo>nFORCE__Screen_Section__c</referenceTo>
        <relationshipLabel>Section Configurations</relationshipLabel>
        <relationshipName>Section_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Configuration</label>
    <nameField>
        <displayFormat>SC-{000000000}</displayFormat>
        <label>Section Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/nFORCE__View__c.object
<CustomObject>
    <label>Screen View</label>
    <nameField>
        <displayFormat>VIEW-{000000000}</displayFormat>
        <label>View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UIRemoveGroupController.cls
public with sharing class UIRemoveGroupController
{
    public String RecordId {get; set;}
    transient Savepoint sp;

    public nFORCE__Group__c starting_group;
    
    public UIRemoveGroupController(ApexPages.StandardController stdController)
    {
        RecordId = stdController.getId();
    }
    
    public void removeGroupItems()
    {
        /*
            Removal of all items associated to a Group in the following order.
            Screen Sections (Section Configs by default)
            Screen Views
            Screens
            Route Groups
            Routes
            Field Configs
        */
    
        nFORCE__Group__c theGroup = [SELECT ID, Name FROM nFORCE__Group__c WHERE Id = :RecordId];
        starting_group = theGroup;
        
        List<nFORCE__Route_Group__c> routeGroups = new List<nFORCE__Route_Group__c>();
        routeGroups = [SELECT ID, nFORCE__Route__c FROM nFORCE__Route_Group__c WHERE nFORCE__Group__c = :theGroup.Id];
        List<Id> routeGroupIds = new List<Id>();
        for (nFORCE__Route_Group__c r : routeGroups)
        {
            routeGroupIds.add(r.nFORCE__Route__c);
        }
        
        List<nFORCE__Route__c> allRoutes = new List<nFORCE__Route__c>();
        allRoutes = [SELECT ID, nFORCE__Screen__c FROM nFORCE__Route__c WHERE Id IN :routeGroupIds];
        
        //Getting Route Groups from other Groups
        List<nFORCE__Route_Group__c> additionalRouteGroups = [SELECT Id, nFORCE__Route__c, nFORCE__Group__c FROM nFORCE__Route_Group__c WHERE nFORCE__Route__c IN :routeGroupIds];
        List<nFORCE__Route__c> routes = new List<nFORCE__Route__c>();
        for (nFORCE__Route__c r : allRoutes)
        {
            Boolean doDelete = true;
            for(nFORCE__Route_Group__c rg : additionalRouteGroups)
            {
                if(rg.nFORCE__Group__c != theGroup.Id)
                {
                    //the Route Group is attached to a different Group, so we cannot delete the associated Route
                    doDelete = false; 
                }    
            }
            
            if (doDelete)
            {
                routes.add(r);
            }
        }
        
        Set<Id> routeIDs = new Set<Id>();
        for(nFORCE__Route__c rt : routes)
        {
            routeIDs.add(rt.Id);
        }
        
        //first Field Config list for those that are Route-only
        List<nFORCE__Field_Configuration__c> fieldConfigs = [SELECT ID FROM nFORCE__Field_Configuration__c WHERE nFORCE__Route__c IN :routeIDs AND nFORCE__Screen_Section__c = null];
           
        List<Id> screenIds = new List<Id>();
        for (nFORCE__Route__c r : routes)
        {
            screenIds.add(r.nFORCE__Screen__c);
        }
        
        List<nFORCE__Screen__c> screens = new List<nFORCE__Screen__c>();
        screens = [SELECT ID FROM nFORCE__Screen__c WHERE Id IN :screenIds];
        
        List<nFORCE__Screen_Section__c> screenSections = new List<nFORCE__Screen_Section__c>();
        screenSections = [SELECT ID, nFORCE__Screen__c, nFORCE__Screen_View__c FROM nFORCE__Screen_Section__c WHERE nFORCE__Screen__c IN :screenIds];
        List<Id> screenSectionIds = new List<Id>();
        for (nFORCE__Screen_Section__c ss : screenSections)
        {
            screenSectionIds.add(ss.Id);
        }
        
        //getting children Screen Sections that would not be found in the above Id list, then combining into original list
        List<nFORCE__Screen_Section__c> childScreenSections = new List<nFORCE__Screen_Section__c>();
        childScreenSections = [SELECT ID, nFORCE__Screen__c, nFORCE__Screen_View__c FROM nFORCE__Screen_Section__c WHERE nFORCE__Parent_Screen_Section__c IN :screenSectionIds];
        screenSections.addAll(childScreenSections);
        
        Set<Id> parentScreenIds = new Set<Id>();
        for(nFORCE__Screen_Section__c ss : childScreenSections)
        {
            if(!screenIds.contains(ss.nFORCE__Screen__c))
            {
                parentScreenIds.add(ss.nFORCE__Screen__c);
            }
        }
        
        //getting parent Screens that would not be found in the above Id list, then combining into original list
        List<nFORCE__Screen__c> parentScreens = new List<nFORCE__Screen__c>();
        parentScreens = [SELECT ID FROM nFORCE__Screen__c WHERE Id IN :parentScreenIds];
        screens.addAll(parentScreens);
        
        List<nFORCE__Section_Configuration__c> sectionConfigurations = new List<nFORCE__Section_Configuration__c>();
        sectionConfigurations = [SELECT ID, nFORCE__Layout__c FROM nFORCE__Section_Configuration__c WHERE nFORCE__Screen_Section__c IN: screenSectionIds];
        
        //separate Field Config list for those that are SS-only, then combine lists
        List<nFORCE__Field_Configuration__c> ssFieldConfigs = [SELECT ID FROM nFORCE__Field_Configuration__c WHERE nFORCE__Screen_Section__c IN :screenSectionIds AND nFORCE__Route__c = null];
        fieldConfigs.addAll(ssFieldConfigs);
                
        List<Id> screenViewIds = new List<Id>();
        for (nFORCE__Screen_Section__c ss : screenSections)
        {
            screenViewIds.add(ss.nFORCE__Screen_View__c);
        }
        
        List<nFORCE__View__c> screenViews = new List<nFORCE__View__c>();
        screenViews = [SELECT ID FROM nFORCE__View__c WHERE Id IN :screenViewIds];
        
        Set<Id> layoutIDs = new Set<Id>();
        List<nFORCE__Layout__c> layouts = new List<nFORCE__Layout__c>();
        for (nFORCE__Section_Configuration__c sc : sectionConfigurations )
        {
            layoutIDs.add(sc.nFORCE__Layout__c);
        }
        layouts = [SELECT ID FROM nFORCE__Layout__c WHERE Id IN: layoutIDs];
        
        Integer numberOfItems = screenSections.size() + screenViews.size() + screens.size() + routeGroups.size() + routes.size() + layouts.size() + fieldConfigs.size();
        
        sp = Database.setSavepoint();
        System.debug('Number of Items to Delete ::: ' + numberOfItems );
        delete layouts;
        delete screenSections;
        delete screenViews;
        delete screens;
        delete routeGroups;
        delete routes;
        delete fieldConfigs;
    }
    
    public PageReference groupRedirect()
    {
        try
        {
            removeGroupItems();
            
            PageReference group_page = new ApexPages.StandardController(starting_group).view();
            group_page.setRedirect(true);   
            return group_page;            
        }
        catch(Exception e) { Database.rollback(sp); ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Deletion error:  ' + e));  return null;
        }
    }           

}